### PR TITLE
Treat numbers as safe filename characters

### LINKED ISSUE #203: Numbers should be safe characters in file names
If the attachment for the "Exercise with attachment" is named for example "2.zip", the name for that file will be just ".zip" in the database because numbers are not considered as safe characters:

https://github.com/Aalto-LeTech/a-plus/blob/a86bf/lib/helpers.py#L62

### PR DESCRIPTION
**Pull request by ttsirkia**
Fixes #203

### CODE REVIEW

**Comment by teemulehtinen** [comment]
retest this please

**Comment by ttsirkia** [comment]
Maybe this PR just blows everything up and should not be merged :smile:

**Comment by teemulehtinen** [comment]
Tuskinpa, luulin jo että plustest alkoi toimia, mutta.. "xvfb-run: error: Xvfb failed to start" 
retest this please

**Comment by ttsirkia** [comment]
:hatched_chick: :+1:

**Pull request merged**
