### PR TITLE
Indentation for third level entries in TOC view

### PR DESCRIPTION
**Pull request by piehei**
This implements #336.

Any comments?

### CODE REVIEW

**Comment by raphendyr** [comment]
That looks a big ugly hack. Any better solutions?

**Comment by piehei** [comment]
Yes it does haha. 

I'm not too sure about the internals so just checking the entry's number was an easy way to implement this without touching the view logic itself.

Would you find it better to add something like indent: True to each entry object and do it in the view?

**Comment by jrp6** [comment]
Isn't the 'correct' way to do it to have a nested list, like this: https://developer.mozilla.org/en-US/docs/Learn/HTML/Introduction_to_HTML/HTML_text_fundamentals#Nesting_lists

**Comment by teemulehtinen** [comment]
I believe nested lists might/should already be produced. Maybe there is styling issue for ul.toc? Or ul.toc > li > ul.toc etc..

**Comment by jrp6** [comment]
`_children.html` looks to me like it _should_ produce a nested list, but what I'm seeing in the inspector is
```
  <li>
    <h3>
      <a href="/def/current/k01/" class="">1. Kierros 1</a>
    </h3>
    <h4>
      <small>21.8.2017 maanantai 14:00 – 20.9.2017 keskiviikko 12:00</small>
    </h4>
</li><li>
  <a href="/def/current/k01/osa01/" class="">1.1 Luku 1.1: Kurssin esittely</a>
</li>
etc
```

**Comment by raphendyr** [comment]
I'm not sure if we have any courses with third level to test this with.  @jrp example only has first and second levels.

**Comment by jrp** [comment]
Hi all, FYI, that sent an update to @jrp (me) when it should have gone to @jrp6 -- I've never even heard of your project. 

Good luck with the nesting.

**Comment by raphendyr** [comment]
Huargh... Didn't even look. Expected first tab to be person in thread instead of first match... I'm missing irssi times.

**Comment by raphendyr** [comment]
Yep. A+ rendering of that html should be changed. 1.1.1. should be child for 1.1.

And yes, that is 3 levels (1.1.1.). First level is always the title, which contains a list of subtitles (1.1. second level and 1.1.1. for third). Technically, we can have as many levels, so the template should be recursive.

**Comment by teemulehtinen** [comment]
There is a template bug in _children.html
`{% if entry.down == 'level' %}
{% if entry.down %}
<ul class="toc">
{% elif entry.up %}
</ul>
{% endif %}
{% elif entry|is_listed %}`
The first if should be entry.type == 'level'

**Comment by piehei** [comment]
@teemulehtinen's suggestion fixes this. I already implemented it recursively but this is better of course.

screenshot_20180608_170647

**Comment by raphendyr** [comment]
I didn't like those extra newlines :)  If only you would have fixed the indentation instead..

**Pull request closed without merging**
