### PR TITLE
Introduce learning analytics support

### PR DESCRIPTION
**Pull request by teemulehtinen**
Includes javascript client for real time data visualization on learners' progress and effort as well as service API extension to connect external analytics tools to the system. - a master's thesis contribution

### CODE REVIEW

**Comment by Plustest** [comment]
Build finished.

**Comment by Plustest** [comment]
Build finished.

**Comment by Plustest** [comment]
Build finished.

**Comment by Plustest** [comment]
Build finished.

**Comment by Plustest** [comment]
Build finished.

**Comment by teemulehtinen** [comment]
retest this please

**Pull request merged**
