### PR TITLE
Add new parameters to the grader protocol documentation.

### PR DESCRIPTION
**Pull request by Mankro**

### CODE REVIEW

**Comment by Plustest** [comment]
Can one of the admins verify this patch?

**Comment by teemulehtinen** [comment]
add to whitelist

**Comment by Mankro** [comment]
I don't really understand these comments. Is there something I should do? Why would a README file cause a build failure?

**Comment by teemulehtinen** [comment]
Nothing for you to do! The automatic testing environment just broke due to another pull request for master branch (the python requirements there break the testing platform).

**Pull request merged**
