### PR TITLE
Tag removal

### PR DESCRIPTION
**Pull request by jrp6**
And a couple bugfixes.

I'd prefer no merge before Aalto-LeTech/django-colortag#3

### CODE REVIEW

**Comment by raphendyr** [comment]
https://github.com/Aalto-LeTech/django-colortag/pull/3

is merged, so requirements can be updated.

**Comment by raphendyr** [comment]
apparently locale files require fixing before merge :/

**Comment by jrp6** [comment]
```
++<<<<<<< 650f30846264f43a572ea2185be14bb197c9c4ef
 +"POT-Creation-Date: 2018-06-26 18:11+0300\n"
++=======
+ "POT-Creation-Date: 2018-06-29 14:17+0300\n"
++>>>>>>> Add popover buttons for filtering and removal
```
Oh gee, what a horrible conflict...

**Comment by raphendyr** [comment]
Github was boring and just gave me grey buttons :D

**Pull request merged**
