### PR TITLE
Security api fix! Also fixes #304

### LINKED ISSUE #304: API: Submission sheet won't work correctly with groups.
```python
        for profile in s.submitters.all():
            row['UserID'] = profile.user.id
            row['StudentID'] = profile.student_id
            row['Email'] = profile.user.email
            sheet.append(row)
```
on https://github.com/Aalto-LeTech/a-plus/blob/master/exercise/api/submission_sheet.py#L107

Above code will change dictionary for previous lines. Second student would need a copy of the dictionary.

### PR DESCRIPTION
**Pull request by teemulehtinen**

### CODE REVIEW

**Comment by Plustest** [comment]
Build finished.

**Comment by raphendyr** [comment]
Reviewed. Ok.

**Comment by teemulehtinen** [comment]
retest this please

**Comment by Plustest** [comment]
Build finished.

**Comment by teemulehtinen** [comment]
retest this please

**Comment by teemulehtinen** [comment]
retest this please

**Pull request merged**
