### PR TITLE
Django colortag

### PR DESCRIPTION
**Pull request by jrp6**
Reimplement UserTag using Aalto-LeTech/django-colortag

### CODE REVIEW

**Comment by Plustest** [comment]
Can one of the admins verify this patch?

**Comment by jrp6** [comment]
A+ could be simplified by rendering the tags using the templatetags from django_colortag. However, it doesn't use font_color so tags with light colour background are difficult to read, so I'm staying with rendering the tags in A+ until that's fixed

**Comment by raphendyr** [comment]
add to whitelist

**Comment by raphendyr** [comment]
Check this line https://github.com/Aalto-LeTech/django-colortag/blob/master/django_colortag/widgets.py#L22

It adds correct class based on what font color should be used.

**Pull request merged**
